/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.g18214.dzaikov.t3;

import java.util.ArrayList;
import java.util.List;

public class App {
  private static void printStrings(String... strings) {
    for (String s : strings) {
      System.out.println(s);
    }
  }

  public static void main(String[] args) {
    List<Thread> threads = new ArrayList<>();
    Object monitor = new Object();
    for (int i = 0; i < 4; i++) {
      int I = i;
      threads.add(
          new Thread(
              () -> {
                String[] str = new String[100];
                for (int j = 0; j < 100; j++) {
                  str[j] = "t" + I + ":" + j;
                }
                synchronized (monitor) {
                  printStrings(str);
                }
              },
              "t" + I));
    }
    threads.forEach(Thread::start);
  }
}
