/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.g18214.dzaikov.t5;

public class App {
    public static void main(String[] args) {
        Thread child = new Thread(() -> {
            long ms = 0;
            while (!Thread.currentThread().isInterrupted()) {
                try {
                    System.out.println(ms + " ms.");
                    ms += 100;
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    System.out.println("Child thread is interrupted.");
                    break;
                }
            }
        }, "Child");
        child.start();
        try {
            Thread.sleep(2000);
            child.interrupt();
            child.join();
        } catch (InterruptedException ignored) {

        }
    }
}