/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.dzaikov.t11;

import java.util.concurrent.Semaphore;

public class App {
    public static void main(String[] args) {
        Semaphore semaphore1 = new Semaphore(0);
        Semaphore semaphore2 = new Semaphore(1);
        Thread child =
                new Thread(
                        () -> {
                            for (int i = 0; i < 10; i++) {
                                try {
                                    semaphore1.acquire();
                                    System.out.println("Child.");
                                } catch (InterruptedException ignored) {

                                } finally {
                                    semaphore2.release();
                                }
                            }
                        },
                        "Child");
        child.start();
        for (int i = 0; i < 10; i++) {
            try {
                semaphore2.acquire();
                System.out.println("Parent.");
            } catch (InterruptedException ignored) {

            } finally {
                semaphore1.release();
            }
        }
    }
}
