/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.xml;

public class App {
    public static void main(String[] args) {
        XmlToDataBase.doWork("persons_1.xml");
    }
}
