/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.g18214.dzaikov.t2;

public class App {
  public static void main(String[] args) {
    Thread child =
        new Thread(
            () -> {
              for (int i = 0; i < 10; i++) {
                System.out.println("Child.");
              }
            },
            "Child");
    child.start();
    try {
      child.join();
    } catch (InterruptedException e) {
      System.err.println("InterruptedException");
    }
    for (int i = 0; i < 10; i++) {
      System.out.println("Parent.");
    }
  }
}
