/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xml1;


import javax.xml.stream.XMLStreamException;
import java.io.FileNotFoundException;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Collectors;


public class App {
    public static void main(String[] args) {
        Map<String, Person> map = new TreeMap<>();
        Map<String, Person> nameMap = new TreeMap<>();
        Map<String, String> idsToRemove = new TreeMap<>();
        try {
            Parser.restore1(map, nameMap, idsToRemove, false);
            Parser.restore1(map, nameMap, idsToRemove, true);
            Parser.restore2(map, nameMap, idsToRemove);

            System.out.println(map.keySet().size());
            System.out.println(map.values().stream().filter(person -> person.getFirstName() != null).count());
            System.out.println(map.values().stream().filter(person -> person.getSecondName() != null).count());
            System.out.println(map.values().stream().filter(person -> person.getGender() != null).count());
            System.out.println(map.values().stream().filter(person -> person.getSiblingsNum() != null).count());
            System.out.println(map.values().stream().filter(person -> person.getChildrenNum() != null).count());
            System.out.println(map.values().stream().filter(person -> person.getSpouseName() != null).count());
            System.out.println(map.values().stream().filter(person -> person.getParents().size() == 1 || person.getParents().size() == 2).count());
            System.out.println(map.values().stream().filter(person -> person.getSiblings().size() == person.getSiblingsNum()).count());
            System.out.println(map.values().stream().filter(person -> person.getChildren().size() == person.getChildrenNum()).count());
        } catch (FileNotFoundException | XMLStreamException e) {
            e.printStackTrace();
        }
        XMLProcessing.writeDataToFile(map, nameMap, "persons_1.xml", "src/main/resources/persons.xsd");
        XMLProcessing.writeXSLT("personsTable.html", "persons_1.xml", "src/main/resources/persons.xsd", "persons.xsl");
    }
}
